### ISSUE TITLE
关于BCM943602CS的长度

### ISSUE THREAD

**Issue by QilsF** [xiaooloong/asrock_deskmini310_hackintosh#3]
有个问题质询一下，我看了一下bcm943602cs的长度要比dw1560的长，不清楚主板能不能放进去，是不是没法用螺丝固定呀。

**Comment by xiaooloong** [comment]
可以放进去。转接板中间的孔位可以把螺丝拧上。
转接板背面紧贴南桥，我贴了胶带。
转接后整体比较厚，我剪了2mm吸管垫在ssd螺丝上。

**Comment by QilsF** [comment]
好的，非常感谢。
